# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitter
      POSTGRES_USER: user
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 2000:8080

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    
  frontend:
    build: 
      context: frontend/twitter_clone
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:8080
  