# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.5.10
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: twitter
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 2000:8080

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - docker.env
    
  frontend:
    build: 
      context: frontend/twitter_clone
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:8080
  
